services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    image: teste_tecnico_bsatech_renato_node:23-alpine
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production